//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	[System.Serializable]
	public class BlueprintObject
	{
		private string name;
		private Sprite sprite;
		private float x;
		private float y;


		public BlueprintObject (string name, Sprite sprite, float x_location, float y_location)
		{
			this.name = name;
			this.sprite = sprite;
			x = x_location;
			y = y_location;
		}

		public string Name {
			get {
				return name;
			}
		}

		public Sprite Sprite {
			get {
				return sprite;
			}

		}

		public float X {
			get {
				return x;
			}
		}

		public float Y  {
			get {
				return y;
			}
		}

	}

}