//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using ST;

namespace AssemblyCSharp
{
	[System.Serializable]
	public class Blueprint
	{
		private List<BlueprintObject> objects = new List<BlueprintObject>();
		private string type;
		private List<STSpriteInfo> m_sprites;
		public static int windowCount = 0;

		public Blueprint (string type, List<STSpriteInfo> sprites)
		{
			this.m_sprites = sprites;
			if (type == "windows") {
				createWindowsBp();

			}
			this.type = type;
		}

		public void addBlueprintOject(BlueprintObject bpo) {
			objects.Add (bpo);
		
		}

		public List<BlueprintObject> getBlueprintObjects()  {
			return objects;
		}

		public string Type {
			get {
				return type;
			}
		}

		private void createWindowsBp() {


			for (int i = 0; i < 2; i++) {
				for (int j = 0; j < 3; j++) {
					int random = UnityEngine.Random.Range(0, m_sprites.Count);
					int exists = UnityEngine.Random.Range(0, 3);
					if (exists > 0) {
						//Debug.Log ("-- create window   ");
						BlueprintObject obj = new BlueprintObject("window_"+windowCount, m_sprites[random].target, 10 + j * 30, 10 + i*40);
						windowCount++;
						objects.Add(obj);
					}
				}
			}

		}


	}
}

